controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time : true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pid_controller:
      type: pid_controller/PidController

pid_controller:
  ros__parameters:
    dof_names:
      - "joint_1"
      - "joint_2"
      - "joint_3"
      - "joint_4"
      - "joint_5"
      - "joint_6"
    command_interface: position
    reference_and_state_interfaces: ["position"]
    gains:
      joint_1: {p: 2.0, i: 0.1, d: 0.01}
      joint_2: {p: 1.5, i: 0.1, d: 0.02}
      joint_3: {p: 1.2, i: 0.2, d: 0.015}
      joint_4: {p: 1.0, i: 0.05, d: 0.01}
      joint_5: {p: 0.9, i: 0.02, d: 0.005}
      joint_6: {p: 1.3, i: 0.15, d: 0.02}
